algorithm_kwargs:
  batch_size: 4
  eval_freq: 2
  num_epochs: 120
  start_epoch: 0
amp: false
dataset_kwargs:
  batch_size: 4
  crop_size: 512
  dataset: ade20k
  image_size: 512
  normalization: deit
  num_workers: 10
  split: train
inference_kwargs:
  im_size: 512
  window_size: 512
  window_stride: 512
log_dir: seg_base_think_linear_mask_120epoch
net_kwargs:
  backbone: deit_base_patch16_224
  d_model: 768
  decoder:
    n_cls: 150
    name: linear
  distilled: false
  drop_path_rate: 0.1
  dropout: 0.0
  image_size: !!python/tuple
  - 512
  - 512
  n_cls: 150
  n_heads: 12
  n_layers: 12
  normalization: deit
  patch_size: 16
  pretrained_path: /home/aho/rldeit/HydraViT.tar
optimizer_kwargs:
  clip_grad: null
  epochs: 120
  iter_max: 303240
  iter_warmup: 0.0
  lr: 0.001
  min_lr: 1.0e-05
  momentum: 0.9
  opt: sgd
  poly_power: 0.9
  poly_step_size: 1
  sched: polynomial
  weight_decay: 0.0
resume: false
thinking_kwargs:
  loss_weights: null
  stages:
  - 3
  - 6
  threshold: 0.5
version: normal
world_batch_size: 8
